title: "Poldrack Lab Guide"
author: The Poldrack Lab
execute:
  execute_notebooks: "off"
repository:
  url: https://github.com/poldracklab/poldracklab.github.io
html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
